# Use the public MySQL image
FROM public.ecr.aws/bitnami/mysql:8.0

ENV MYSQL_ROOT_PASSWORD=wiley123
ENV MYSQL_PASSWORD=wiley123
ENV MYSQL_USER=wiley
ENV MYSQL_DATABASE=orderbook

ENV MYSQL_SLOW_QUERY_LOG=1
ENV MYSQL_SLOW_QUERY_LOG_FILE=/var/log/mysql/slow-queries.log
ENV MYSQL_LONG_QUERY_TIME=1

ENV MYSQL_REPLICATION_MODE=master
ENV MYSQL_REPLICATION_USER=replicator 
ENV MYSQL_REPLICATION_PASSWORD=wiley123


# Copy initialization scripts
COPY src/mysql/init /docker-entrypoint-initdb.d/
