# Use the public MySQL image
FROM public.ecr.aws/bitnami/mysql:8.0

ENV MYSQL_ROOT_PASSWORD=wiley123
ENV MYSQL_PASSWORD=wiley123
ENV MYSQL_USER=wiley
ENV MYSQL_DATABASE=orderbook


# Copy initialization scripts
COPY src/mysql/init /docker-entrypoint-initdb.d/

